# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit the build to Google Play alpha track"
  lane :alpha do
    publish(track: 'alpha')
  end

  desc "Submit the build to Google Play production track"
  lane :production do
    publish(track: 'production')
  end
  
  desc "Submit the build to Google Play"
  lane :publish do |options|
    sh "flutter build appbundle -v --flavor prod"
    changelog_from_git_commits
    upload_to_play_store(
      track: options[:track],
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab'
    )
  end
end
