# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do |lane, options|
    # Avoid generating `README.md`.
    skip_docs
  end

  desc "Prepare build"
  lane :prepare do |options|
    # Choose default track if not specified.
    track = options[:track] || "alpha"

    # Increment version number to one more than currently released version.
    versions = google_play_track_version_codes(track: track)
    version = versions[0] + 1

    # Retrieve version name from Git tag (includes commit hash)
    tag = sh "git describe --tags"

    # Generate changelog from merged pull requests.
    changelog_from_git_commits(merge_commit_filtering: "only_include_merges")

    # Build Flutter app.
    sh "flutter build appbundle -v --flavor prod --build-number=#{version} " +
      "--build-name=#{tag}"
  end
  
  desc "Submit the build to Google Play"
  lane :publish do |options|
    prepare(options)

    # Upload to Google Play.
    upload_to_play_store(
      track: options[:track],
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab"
    )
  end

  desc "Promote alpha track to production on Google Play"
  lane :release do
    track = "alpha"

    # Detect currently released alpha version.
    versions = google_play_track_release_names(track: track)
    version = versions[0]

    # Check that it matches the current commit.
    tag = sh "git describe --tags"
    if tag != version
      UI.abort_with_message! "Cannot promote to production because " +
        "#{tag} is not deployed in #{track}"
    end

    # Promote.
    upload_to_play_store(
      track: track,
      track_promote_to: "production",
      skip_upload_changelogs: true
    )
  end
end
