# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new beta build to Google Play"
  lane :beta do
    sh "flutter build appbundle -v --flavor prod"
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab'
    )
  end

  desc "Submit a new production build to Google Play"
  lane :production do
    sh "flutter build appbundle -v --flavor prod"
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab'
    )
  end
end
