name: Build
on:
  workflow_dispatch:
    # Enable manual run.
  pull_request:
    branches-ignore:
      # Main branch is built and deployed separately.
      # IMPORTANT: Keep consistent with `deploy-main.yml`.
      - main

jobs:
  fastlane-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        uses: ./.github/actions/docker
        with:
          command: ./entrypoint.sh && cd android && bundle exec fastlane prepare
