name: Build
on:
  workflow_dispatch:
    # Enable manual run.
  pull_request:
    branches:
      # Build pull requests against the main branch.
      - main

jobs:
  fastlane-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the application
        uses: ./.github/actions/docker
        with:
          command: ./entrypoint.sh && cd android && bundle exec fastlane prepare
