name: Deploy main to Play Store
on:
  workflow_dispatch:
    # Enable manual run.
    inputs:
      track:
        description: 'Play Store track to use (alpha OR production)'
        required: true
        default: 'alpha'
  push:
    branches:
      # Deploy every merged pull request.
      # IMPORTANT: Keep consistent with `build-pr.yml`.
      - main

jobs:
  fastlane-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy the application
        uses: ./.github/actions/docker
        with:
          command: >
            ./entrypoint.sh && cd android && bundle exec fastlane build
            track:${{ github.event.inputs.track || 'alpha' }}
