name: Release to production in Play Store
on:
  workflow_dispatch:
    # Enable manual run.
  push:
    # Run when version tag is pushed (also happens when GitHub release is
    # published).
    tags:
      - 'v*'

jobs:
  fastlane-promote:
    runs-on: ubuntu-latest
    steps:
      - name: Promote the application
        uses: ./.github/actions/docker
        with:
          command: >
            ./entrypoint.sh && cd android && bundle exec fastlane release
